FROM node:22-alpine

WORKDIR /usr/src/app

# Install app dependencies
COPY package*.json ./
RUN npm install

# Copy application sources
COPY . .

EXPOSE 3000

# Start in watch mode
CMD ["npm", "run", "start:dev"]
