services:
  postgres-db:
    image: postgres:16-alpine
    container_name: nest_postgres_dev
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: tasks_dev_db
    ports:
      - '5432:5432'
    volumes:
      - pgdata_dev:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d tasks_dev_db']
      interval: 5s
      timeout: 5s
      retries: 5

  web-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: nest_app_dev
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: development
      PORT: 3000
      DATABASE_URL: postgresql://postgres:postgrespassword@postgres-db:5432/tasks_dev_db
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      postgres-db:
        condition: service_healthy
    command: >
      sh -c "npm run db:migrate && npm run start:dev"

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins_server
    ports:
      - '8080:8080'
      - '50000:50000'
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  pgdata_dev:
  jenkins_home:

